apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: my-volume
          mountPath: /usr/share/nginx/html
        - name: my-log
          mountPath: /mnt
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: airflow-cluster-dags
    - name: my-log
      persistentVolumeClaim:
        claimName: airflow-cluster-logs
